version: '3'
services:
  postgres-db:
    image: postgres:15
    container_name: findex
    environment:
      POSTGRES_USER: findex_user
      POSTGRES_PASSWORD: findex1234
      POSTGRES_DB: findex
    ports:
      - "5432:5432"
    volumes:
      - db_findex_data:/var/lib/postgresql/data

volumes:
  db_findex_data: